name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          script: |
            cd /var/www/HM-Laravel
            
            # Adjust permissions for the build directory to avoid permission issues
            sudo chown -R www-data:www-data /var/www/HM-Laravel/public/build
            sudo chmod -R 775 /var/www/HM-Laravel/public/build
            
            # Deploy and build process
            sudo -u www-data git pull origin main
            sudo -u www-data composer install
            sudo -u www-data npm install        
            sudo -u www-data npm run build      
            sudo -u www-data php artisan migrate:fresh --seed  
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache
            
            # Restart Apache server
            sudo systemctl restart apache2
